%x and y corner (xc,yc) is the corner closest to the origin,
%sidelength (s) is the same
%and should be 1/4 of the robot length, height is from a random
%distribution, ground should be set to 0 unless and offset is needed.
%This function reshapes the data for cubes to work with the STL files

function [vertices]=cube_vertices(xc,yc,s,height,z0)
vertices=...
[xc,yc,height+z0;...
 xc,yc+s,height+z0;...
 xc,yc,z0;...
 xc,yc,z0;...
 xc,yc+s,height+z0;...
 xc,yc+s,z0;...
 xc+s,yc,height+z0;...
 xc,yc,height+z0;...
 xc+s,yc,z0;...
 xc+s,yc,z0;...
 xc,yc,height+z0;...
 xc,yc,z0;...
 xc+s,yc+s,height+z0;...
 xc+s,yc,height+z0;...
 xc+s,yc+s,z0;...
 xc+s,yc+s,z0;...
 xc+s,yc,height+z0;...
 xc+s,yc,z0;...
 xc,yc+s,height+z0;...
 xc+s,yc+s,height+z0;...
 xc,yc+s,z0;...
 xc,yc+s,z0;...
 xc+s,yc+s,height+z0;...
 xc+s,yc+s,z0;...
 xc+s,yc,height+z0;...
 xc+s,yc+s,height+z0;...
 xc,yc,height+z0;...
 xc,yc,height+z0;...
 xc+s,yc+s,height+z0;...
 xc,yc+s,height+z0;...
 xc+s,yc+s,z0;...
 xc+s,yc,z0;...
 xc,yc+s,z0;...
 xc,yc+s,z0;...
 xc+s,yc,z0;...
 xc,yc,z0];